version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn build
      - persist_to_workspace:
          root: ./
          # must include anything needed by the Dockerfile, mvpstudio.yml, .git, and kube folder
          paths:
            - public
            - config
            - server
            - .mvpstudio
            - Dockerfile
            - .git

  publish:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - run: curl https://raw.githubusercontent.com/MVPStudio/build_setup/master/build_tag_push.sh | bash

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          context: web-cms
      - publish:
          context: dockerhub-publish
          requires:
            - build
          filters:
            branches:
              only: master
