version: 2
jobs:
  build-static:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd static/ && yarn build
      - persist_to_workspace:
          root: ./
          # must include anything needed by the Dockerfile, mvpstudio.yml, .git, and kube folder
          paths:
            - static

  publish-static:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - run: cd static/ && curl https://raw.githubusercontent.com/MVPStudio/build_setup/master/build_tag_push.sh | bash

  build-api:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd api/ && yarn build
      - persist_to_workspace:
          root: ./
          # must include anything needed by the Dockerfile, mvpstudio.yml, .git, and kube folder
          paths:
            - api

  publish-api:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - run: cd api/ && curl https://raw.githubusercontent.com/MVPStudio/build_setup/master/build_tag_push.sh | bash

workflows:
  version: 2
  build-publish:
    jobs:
      - build-static: {}
      - build-api: {}
      - publish-static:
          context: dockerhub-publish
          requires:
            - build-static
          filters:
            branches:
              only: master
      - publish-api:
          context: dockerhub-publish
          requires:
            - build-api
          filters:
            branches:
              only: master